const quotes = [
    "The only way to do great work is to love what you do. – Steve Jobs",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Do not wait to strike till the iron is hot; but make it hot by striking. – William Butler Yeats",
    "In the middle of every difficulty lies opportunity. – Albert Einstein",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "If you're going through hell, keep going. – Winston Churchill",
    "The best way to predict the future is to create it. – Peter Drucker",
    "Hardships often prepare ordinary people for an extraordinary destiny. – C.S. Lewis",
    "Don’t count the days, make the days count. – Muhammad Ali",
    "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
    "Dream big and dare to fail. – Norman Vaughan",
    "Happiness is not something ready-made. It comes from your own actions. – Dalai Lama",
    "Act as if what you do makes a difference. It does. – William James",
    "You miss 100% of the shots you don’t take. – Wayne Gretzky",
    "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
    "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
    "Opportunities don't happen. You create them. – Chris Grosser",
    "Failure will never overtake me if my determination to succeed is strong enough. – Og Mandino",
    "The harder the conflict, the greater the triumph. – George Washington",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "Start where you are. Use what you have. Do what you can. – Arthur Ashe",
    "Life is what happens when you're busy making other plans. – John Lennon",
    "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
    "Your time is limited, so don’t waste it living someone else’s life. – Steve Jobs",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
    "Strive not to be a success, but rather to be of value. – Albert Einstein",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "Be the change that you wish to see in the world. – Mahatma Gandhi",
    "We may encounter many defeats but we must not be defeated. – Maya Angelou",
    "I never dreamed about success. I worked for it. – Estée Lauder",
    "Do what you feel in your heart to be right—for you’ll be criticized anyway. – Eleanor Roosevelt",
    "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. – Jamie Paolinetti",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
    "Perseverance is not a long race; it is many short races one after the other. – Walter Elliot",
    "Success is getting what you want. Happiness is wanting what you get. – Dale Carnegie",
    "Courage is resistance to fear, mastery of fear—not absence of fear. – Mark Twain",
    "Effort only fully releases its reward after a person refuses to quit. – Napoleon Hill",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. – Bruce Lee",
    "Keep going. Everything you need will come to you at the perfect time. – Unknown",
    "Don’t quit. Suffer now and live the rest of your life as a champion. – Muhammad Ali",
    "We generate fears while we sit. We overcome them by action. – Dr. Henry Link",
    "Don’t wish it were easier. Wish you were better. – Jim Rohn",
    "Hustle until your haters ask if you’re hiring. – Unknown",
    "Success is not measured by what you accomplish but by the opposition you have encountered. – Booker T. Washington",
    "Fall seven times and stand up eight. – Japanese Proverb",
    "Every accomplishment starts with the decision to try. – John F. Kennedy",
    "A winner is a dreamer who never gives up. – Nelson Mandela",
    "Be so good they can’t ignore you. – Steve Martin",
    "Small daily improvements over time lead to stunning results. – Robin Sharma",
    "Don’t let the fear of losing be greater than the excitement of winning. – Robert Kiyosaki",
    "You can’t build a reputation on what you are going to do. – Henry Ford",
    "The secret of getting ahead is getting started. – Mark Twain",
    "Go the extra mile. It’s never crowded. – Dr. Wayne D. Dyer",
    "Success doesn’t come to you. You go to it. – Marva Collins",
    "Success isn’t always about greatness. It’s about consistency. – Dwayne Johnson",
    "Your limitation—it’s only your imagination. – Unknown",
    "Don’t stop when you’re tired. Stop when you’re done. – Marilyn Monroe",
    "Good, better, best. Never let it rest. ‘Til your good is better and your better is best. – St. Jerome",
    "Push yourself, because no one else is going to do it for you. – Unknown",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "Great things are done by a series of small things brought together. – Vincent Van Gogh",
    "I can’t change the direction of the wind, but I can adjust my sails to always reach my destination. – Jimmy Dean",
    "Learn as if you will live forever, live like you will die tomorrow. – Mahatma Gandhi",
    "The secret of success is to do the common thing uncommonly well. – John D. Rockefeller Jr.",
    "What we fear doing most is usually what we most need to do. – Tim Ferriss",
    "It’s not whether you get knocked down; it’s whether you get up. – Vince Lombardi",
    "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
    "Act as if it were impossible to fail. – Dorothea Brande",
    "Opportunities don’t happen. You create them. – Chris Grosser",
    "Don’t wait. The time will never be just right. – Napoleon Hill",
    "He who has a why to live can bear almost any how. – Friedrich Nietzsche",
    "Energy and persistence conquer all things. – Benjamin Franklin",
    "It is never too late to be what you might have been. – George Eliot",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. – Mahatma Gandhi",
    "Don’t wish it were easier, wish you were better. – Jim Rohn"
];

const colors = [
    "AliceBlue", "AntiqueWhite", "Aqua", "Aquamarine", "Azure", "Beige", "Bisque", "Black", "BlanchedAlmond", "Blue",
    "BlueViolet", "Brown", "BurlyWood", "CadetBlue", "Chartreuse", "Chocolate", "Coral", "CornflowerBlue", "Cornsilk",
    "Crimson", "Cyan", "DarkBlue", "DarkCyan", "DarkGoldenRod", "DarkGray", "DarkGreen", "DarkKhaki", "DarkMagenta",
    "DarkOliveGreen", "DarkOrange", "DarkOrchid", "DarkRed", "DarkSalmon", "DarkSeaGreen", "DarkSlateBlue",
    "DarkSlateGray", "DarkTurquoise", "DarkViolet", "DeepPink", "DeepSkyBlue", "DimGray", "DodgerBlue", "FireBrick",
    "FloralWhite", "ForestGreen", "Fuchsia", "Gainsboro", "GhostWhite", "Gold", "GoldenRod", "Gray", "Green",
    "GreenYellow", "HoneyDew", "HotPink", "IndianRed", "Indigo", "Ivory", "Khaki", "Lavender", "LavenderBlush",
    "LawnGreen", "LemonChiffon", "LightBlue", "LightCoral", "LightCyan", "LightGoldenRodYellow", "LightGray",
    "LightGreen", "LightPink", "LightSalmon", "LightSeaGreen", "LightSkyBlue", "LightSlateGray", "LightSteelBlue",
    "LightYellow", "Lime", "LimeGreen", "Linen", "Magenta", "Maroon", "MediumAquaMarine", "MediumBlue",
    "MediumOrchid", "MediumPurple", "MediumSeaGreen", "MediumSlateBlue", "MediumSpringGreen", "MediumTurquoise",
    "MediumVioletRed", "MidnightBlue", "MintCream", "MistyRose", "Moccasin", "NavajoWhite", "Navy", "OldLace",
    "Olive", "OliveDrab", "Orange", "OrangeRed", "Orchid", "PaleGoldenRod", "PaleGreen", "PaleTurquoise",
    "PaleVioletRed", "PapayaWhip", "PeachPuff", "Peru", "Pink", "Plum", "PowderBlue", "Purple", "RebeccaPurple",
    "Red", "RosyBrown", "RoyalBlue", "SaddleBrown", "Salmon", "SandyBrown", "SeaGreen", "SeaShell", "Sienna", "Silver",
    "SkyBlue", "SlateBlue", "SlateGray", "Snow", "SpringGreen", "SteelBlue", "Tan", "Teal", "Thistle", "Tomato",
    "Turquoise", "Violet", "Wheat", "White", "WhiteSmoke", "Yellow", "YellowGreen",
    // Extended
    "Amethyst", "Amber", "Apricot", "AshGray", "BabyBlue", "BlackOlive", "BlueSapphire", "BondiBlue", "BrightCerulean",
    "BrightTurquoise", "Bronze", "Byzantine", "CameoPink", "Caramel", "CarnationPink", "Cerulean", "Champagne", "Cherry",
    "Chestnut", "Cinnamon", "CobaltBlue", "Copper", "Corn", "CottonCandy", "Cream", "Daffodil", "Denim", "Eggplant",
    "ElectricBlue", "Emerald", "FernGreen", "Flame", "Flax", "GoldFusion", "GoldenPoppy", "GoldenYellow", "HarvestGold",
    "Iris", "Isabelline", "Jade", "JazzberryJam", "KellyGreen", "LavenderGray", "LimePunch", "Mahogany", "Malachite",
    "Mauve", "MintGreen", "Mustard", "Onyx", "Peach", "Pewter", "PineGreen", "PrussianBlue", "Ruby", "Saffron",
    "Sage", "SandDune", "Scarlet", "Shamrock", "SmokeyTopaz", "SpringBud", "SteelPink", "Taupe", "TigerOrange",
    "TiffanyBlue", "UltraRed", "Viridian", "Watermelon", "Wine", "ZinnwalditeBrown"
];
const generate = document.getElementById("submit");
const content = document.getElementById("content");

function generateRandomBackgroundColor(){
    let randomColorIndex = Math.floor(Math.random() * (colors.length));
    document.body.style.backgroundColor = colors[randomColorIndex];
}

generate.addEventListener("click", (e) => {
    let randomGenerated = Math.floor(Math.random() * (quotes.length));
    generateRandomBackgroundColor();
    content.innerText = quotes[randomGenerated];
})
